"""
## **Project: LinkedIn MCP (Model Context Protocol) "Architect" Agent**

### **1. Core Objective**

Build an automated search and extraction agent to identify **Technical Gatekeepers** in "Hard-to-Abate" industries (Pulp/Paper, Steel, Heavy Ag) who are currently facing high ESG/Carbon penalty liabilities.

### **2. Target Parameters (The Audit Filter)**

* **Industry Focus:** Pulp and Paper Mills, Industrial Heat Processing, Carbon-Intensive Manufacturing.
* **Target Titles:** * *Primary:* Director of Process Engineering, Lead Thermal Engineer, CTO (Technical).
* *Secondary:* Sustainability Director (must have 'Engineer' in profile), Head of Energy Procurement.


* **Keywords:** Pyrolysis, Biochar, Biomass-to-Energy, Carbon Sequestration, Closed-Loop Manufacturing, 12/17 Geometry.

### **3. Operational Logic (The 7:3 Ratio)**

* **Step A (Scrape):** Identify the top 50 global firms in the Pulp and Paper sector.
* **Step B (Cross-Reference):** Match firms against known **ESG Penalty Data** (Companies with high carbon-credit expenditures).
* **Step C (Extract):** Identify the 3 most senior technical individuals at each firm.
* **Step D (Payload Prep):** Generate a "Sovereign Outreach" draft focused on **Thermodynamic Efficiency** and **Patent 12/17**, avoiding "pitch" language.

### **4. Technical Stack Requirements**

* **Integration:** Use LinkedIn API or LinkedIn Sales Navigator MCP.
* **Data Structure:** Output to a CSV/JSON file on the PC/NAS with the following columns: `Name`, `Title`, `Company`, `Estimated Carbon Liability`, `Technical Direct Contact (if available)`.
* **Privacy:** Ensure all scraping adheres to rate-limiting to protect the Sovereign LinkedIn profile from "Dragon" flags.

*(Generated by the model for transparency.)*
"""