# Install PowerShell aliases for job-lead-finder development
# Run this once to set up your development environment

Write-Host "Setting up development environment..." -ForegroundColor Cyan

# Ensure profile exists
if (-not (Test-Path $PROFILE)) {
    New-Item -Path $PROFILE -ItemType File -Force | Out-Null
    Write-Host "Created PowerShell profile" -ForegroundColor Green
}

# Get the project root
$projectRoot = Split-Path -Parent $PSScriptRoot

# Create the aliases block
$aliases = @"

# ========================================
# Job Lead Finder Development Aliases
# Auto-generated by dev-setup.ps1
# ========================================

# Git shortcuts
function gco { git checkout `$args }
function gcb { git checkout -b `$args }
function gaa { git add -A }
function gcm { param(`$msg) git commit -m `$msg }
function gp { git push }
function gpu { git push -u origin `$(git branch --show-current) }
function gs { git status }
function gd { git diff }
function gl { git log --oneline -10 }
function gpl { git pull }

# GitHub CLI shortcuts
function ghpr {
    param(`$base, `$title, `$body)
    & "C:\Program Files\GitHub CLI\gh.exe" pr create --base `$base --title `$title --body `$body
}
function ghprl { & "C:\Program Files\GitHub CLI\gh.exe" pr list }
function ghprv { & "C:\Program Files\GitHub CLI\gh.exe" pr view `$args }
function ghprc { & "C:\Program Files\GitHub CLI\gh.exe" pr checks }

# Python/Testing shortcuts
function jl-test { & "$projectRoot\venv\Scripts\python.exe" -m pytest `$args }
function jl-cov { & "$projectRoot\venv\Scripts\python.exe" -m pytest --cov=app --cov-report=html `$args }

# Docker shortcuts
function jl-up { docker compose up -d }
function jl-down { docker compose down }
function jl-logs { docker compose logs ui --tail 50 }
function jl-ps { docker compose ps }

# Project utility scripts
function jl-upload { & "$projectRoot\scripts\upload-resume.ps1" `$args }
function jl-search { & "$projectRoot\scripts\search-jobs.ps1" `$args }
function jl-reload { & "$projectRoot\scripts\reload-ui.ps1" `$args }

# Quick navigation
function jl-cd { Set-Location "$projectRoot" }

Write-Host "Job Lead Finder aliases loaded!" -ForegroundColor Green
"@

# Check if aliases already exist
$profileContent = Get-Content $PROFILE -Raw -ErrorAction SilentlyContinue
if ($profileContent -and $profileContent.Contains("Job Lead Finder Development Aliases")) {
    Write-Host "Aliases already exist in profile" -ForegroundColor Yellow
    $response = Read-Host "Overwrite existing aliases? (y/N)"
    if ($response -ne 'y' -and $response -ne 'Y') {
        Write-Host "Cancelled" -ForegroundColor Red
        exit 0
    }
    
    # Remove old block
    $pattern = "(?s)# ========================================`n# Job Lead Finder Development Aliases.*?Write-Host.*?Green`n"
    $profileContent = $profileContent -replace $pattern, ""
    Set-Content -Path $PROFILE -Value $profileContent.TrimEnd()
}

# Append aliases
Add-Content -Path $PROFILE -Value $aliases

Write-Host ""
Write-Host "Development environment setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "Available commands:" -ForegroundColor Cyan
Write-Host "  Git: gco, gcb, gaa, gcm, gp, gpu, gs, gd, gl, gpl" -ForegroundColor White
Write-Host "  GitHub: ghpr, ghprl, ghprv, ghprc" -ForegroundColor White
Write-Host "  Testing: jl-test, jl-cov" -ForegroundColor White
Write-Host "  Docker: jl-up, jl-down, jl-logs, jl-ps" -ForegroundColor White
Write-Host "  Project: jl-upload, jl-search, jl-reload, jl-cd" -ForegroundColor White
Write-Host ""
Write-Host "Reload your profile to activate:" -ForegroundColor Yellow
Write-Host "  . `$PROFILE" -ForegroundColor White

# Offer to reload now
Write-Host ""
$response = Read-Host "Reload profile now? (Y/n)"
if ($response -eq '' -or $response -eq 'y' -or $response -eq 'Y') {
    . $PROFILE
    Write-Host "Profile reloaded!" -ForegroundColor Green
}
